### ISSUE TITLE
direct matching round

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#12]
Should we have a "direct matching round" prior to the random matching that we currently have. In this scenario, if a mentor+mentee [air mark each other as preferred, and no one else asks for them, we could match them every time. This would allow pods from previous years to maintain themselves in future years.

**Comment by TStarkenburg** [comment]
Made a start of implementing this: checking matched preferences for all mentee-mentors combinations before doing any normal matching round.
Have not double checked whether it works as supposed yet though.

**Comment by agurvich** [comment]
Copying relevant snippet from my comment on @TStarkenburg 's PR. 

I am realizing now that the direct matching round could "fail" in a sense if a mentor prefers more mentees than they have capacity for (and all those mentees prefer them as well). In that scenario the ordering of the mentee list would determine who gets to be matched with that mentor. (i.e. a post doc who prefers 3 grad students but only has capacity for 2 will end up leaving 1 grad student out if they all prefer the post doc as well).

**Comment by TStarkenburg** [comment]
So start from mentors instead of mentees, save which direct matching they have and if needed order the direct matching-mentees for this mentor on role/seniority and number of mentors requested and then match the ones you can?

**Comment by agurvich** [comment]
I was able to do as you suggested and order mentees:
1. by number of mentors requested
2. rank
3. number of mentors preferred 

That way if two grad students prefer the same post doc but one of them *also* prefers a different post doc (and they both want the same number of mentors) then the grad student who only prefered 1 person has priority. At the same time, both grad students have lower priority to an undergrad who wants that postdoc. 

I'm not sure I love that, I think it makes it extremely difficult for postdocs to get a faculty mentor they list as a preference since undergrads and grad students who are requesting the same number of mentors will have priority. Maybe something to consider changing.

**Comment by TStarkenburg** [comment]
I think the case you're worrying about may not happen that often as I think students (grad and undergrad) are more likely to request more mentors than postdocs (students have more options for mentors, and they benefit more from having multiple level mentors)? But this is something we can check for our fake data, our new fake data, and then reconsider.

An alternative option is to switch your 2. and 3.?

**Comment by agurvich** [comment]
ah good point, you're probably right that 1. probably prevents the situation i'm nervous about happening from happening. in that case, I think I'll go ahead and merge this PR!
