### ISSUE TITLE
make minimize metrics -> maximize metrics

### ISSUE THREAD

**Issue by agurvich** [CIERA-Northwestern/JEDI_ext_mentorship#25]
in particular, handle whether metrics become 0 and if so, either redefine the metric (1-metric? 1/metric?)

**Comment by TStarkenburg** [comment]
So, the minimize metrics were already maximizing (1-metric). The problem was actually with metrics to maximize that actually turned out to be == 0 for all networks. So then the combined metric (as we use multiply as default) would be equal to 0 for all networks too. 
I now set the metrics to maximize (and the (1-metric)) to a minimum value of 0.01 if they are equal to 0.
